# Generated by Django 4.1.5 on 2023-01-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_provider", "0003_remove_jobprovider_applicants_job_applicants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobprovider",
            name="company_logo",
            field=models.ImageField(blank=True, null=True, upload_to="company_logos"),
        ),
    ]
