# Generated by Django 4.1.5 on 2023-01-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_provider", "0007_alter_job_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobprovider",
            name="jobs",
            field=models.ManyToManyField(
                blank=True, related_name="job_providers", to="job_provider.job"
            ),
        ),
    ]
