# Generated by Django 4.1.5 on 2023-01-03 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("job_hunter", "0001_initial"),
        ("job_provider", "0001_initial"),
        ("user_profile", "0002_alter_cictuser_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobhunter",
            name="applied_jobs",
            field=models.ManyToManyField(blank=True, to="job_provider.job"),
        ),
        migrations.AddField(
            model_name="jobhunter",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user_profile.cictuser"
            ),
        ),
    ]
