# Generated by Django 4.1.5 on 2023-01-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_hunter", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobhunter",
            name="applied_jobs",
        ),
    ]
