# Generated by Django 4.1.5 on 2023-01-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_hunter", "0003_remove_jobhunter_applied_jobs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobhunter",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes"),
        ),
    ]
