# Generated by Django 4.1.5 on 2023-01-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cictuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("job-hunter", "Job Hunter"),
                    ("job-provider", "Job Provider / Company"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
